spring:
  datasource:
    url: jdbc:mysql://qianfeng1.qfjava.cn:8300/hotelsix?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qishimeiyoumima
    type: com.alibaba.druid.pool.DruidDataSource #连接池的类型
  mvc:
    view:
      suffix: .html
  redis:
    port: 8400
    host: qianfeng1.qfjava.cn
    password: redis001
    jedis:
      pool:
        min-idle: 10
        max-active: 1024
        max-idle: 100
pagehelper:
  helper-dialect: mysql #不同的数据库分页语句可能不一样,
  params: count=countsql
  reasonable: true
  support-methods-arguments: true

